### ISSUE TITLE
Settings Page

### ISSUE THREAD

**Issue by harshptl14** [clubgamma/RiddlesWorld#22]
### Need one Setting page which includes this toggles
      1. Dark mode
      2. Sound effects
      3. Contributors section
      4. About this OpenSource Contribution thing

Make sure to follow the theme of the application. Just see which widget was used in other container types of things.

Add this setting button on the right side of the appBar in HomeScreen.

**Comment by pushpulldecoder** [comment]
I would like to implement it.

- [ ] Dark mode

- [ ] Sound effects

- [ ] Contributors section

- [ ] About open source cotribution
