### ISSUE TITLE
Dark mode

### ISSUE THREAD

**Issue by harshptl14** [clubgamma/RiddlesWorld#24]
### **DARK MODE REQUIRED**
For now, in application white is a major color with the contrast of black👀

Include the dark mode feature which is the reverse of the theme of the application🔀

    Major color = Black⚫
    Minor / Contrast color = white⚪
 
Make sure to make a toggle in the Settings page✳

Make sure you see whether the [Settings page](https://github.com/clubgamma/RiddlesWorld/issues/22) is ready or not because this toggle will be situated at the settings page.

**Comment by diegoalvis** [comment]
I can help with this, feel free to assign the issue to me 🙂

**Comment by harshptl14** [comment]
Hey @diegoalvis, I am waiting for [this](https://github.com/clubgamma/RiddlesWorld/pull/26) response, If I won't get any response in 1-2 days, I will assign you this issue for sure👍

And till then, you can work on some other issues 🎯

**Comment by harshptl14** [comment]
Hey, @diegoalvis, you can start working on this issue!

**Comment by diegoalvis** [comment]
@harshptl14  Added in #45
