### ISSUE TITLE
Sound Effects

### ISSUE THREAD

**Issue by harshptl14** [clubgamma/RiddlesWorld#32]
### **ADD THE SOUND EFFECTS**

As you have seen, most of the time game has some sound effects on tapping the list of levels, or after winning the level👀

So add some sound🎶 effects for tapping the List of Riddles and for the result page which you can find [here](https://github.com/clubgamma/RiddlesWorld/blob/master/lib/universal/result.dart)

**Feel free to commit if you have any queries regarding this📌**

**Comment by bibekpanda55** [comment]
I can add that sounds please assign this issue to me

**Comment by bibekpanda55** [comment]
@harshptl14   I have added the animation sounds on every list page and also on result page as mentioned in this issue please check it and approve it if you think your issue is solved.

**Comment by bibekpanda55** [comment]
@harshptl14  I have solved this issue and have made a PR regarding this please review and merge it

**Comment by harshptl14** [comment]
Thank you @bibekpanda55, your PR is merged!
